
title: PATCHARAMAI HUAJAIPET
#logo: /assets/img/headshot_circle.png
description: Personal academic website for PATCHARAMAI HUAJAIPET, PhD student in Nanoscience and nanotechnology, Faculty of Science, Chiang Mai University, Thailand
#description: text below image
I am curently do the research at the Division of Applied Chemistry, Graduate School of Engineering, The University of Osaka, Japan 
#show_downloads: true
theme: jekyll-theme-minimal
